<a href="https://colab.research.google.com/github/pammyyAnn/Advance-Data-Visualization-Lab11/blob/main/Advance_Data_Visualization_Lab_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
price = [2, 1, 10] 
type(price)

list

In [2]:
quantity_sold = [17, 40, 1] 
type(quantity_sold)


list

In [8]:
import numpy as np

In [10]:
price_array = np.array(price) 
quantity_sold_array = np.array(quantity_sold) 
type(price_array)


numpy.ndarray

In [11]:
price_array * quantity_sold_array

array([34, 40, 10])

In [12]:
cost_array = np.array([0.25, 0.50, 5.00])

In [13]:
profit_array = price_array - cost_array 
print(profit_array)


[1.75 0.5  5.  ]


In [14]:
profit_array > 2.00

array([False, False,  True])

In [15]:
price_array = price_array + [7] 
print(price_array)


[ 9  8 17]


In [16]:
price_array = price_array - [7]

In [17]:
price_array = np.append(price_array, 7) 
print(price_array)


[ 2  1 10  7]


In [18]:
price_array = np.append(price_array, [4.50, 3, 4, 9]) 
print(price_array)


[ 2.   1.  10.   7.   4.5  3.   4.   9. ]


In [19]:
print(price_array.dtype)

float64


In [20]:
price_array = np.delete(price_array, -1) 
print(price_array)


[ 2.   1.  10.   7.   4.5  3.   4. ]


In [21]:
price_array[2] = 12 
print(price_array)


[ 2.   1.  12.   7.   4.5  3.   4. ]
